services:
  sophiacircle:
    image: vekeb71985/sophiacircle:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped